/*
 * This source file was generated by the Gradle 'init' task
 */
package org.wharvex.fixjflap;

import java.io.File;
import java.nio.file.Files;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    FileLoader fileLoader = new FileLoader(
        "C:\\Users\\tgudl\\OneDrive\\KingfisherProjects\\MyJFLAP");

    File[] javaFiles = fileLoader.getJavaFiles();

    FileLoader.replaceLinesInFiles(javaFiles, "import gui.",
        "import org.wharvex.jflap.gui.");

  }
}
