/*
 * This source file was generated by the Gradle 'init' task
 */
package org.wharvex.fixjflap;

import java.io.File;
import java.nio.file.Files;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    FileLoader fileLoader = new FileLoader(
        "C:\\Users\\tgudl\\OneDrive\\KingfisherProjects\\MyJFLAP");

    File[] javaFiles = fileLoader.getJavaFiles();

    for (File file : javaFiles) {
      var lines = FileLoader.getAllLines(file);
      var packageDeclarationLineNum = 1;
      boolean packageDeclarationFound = false;
      var lastLineNum = lines.size();
      while (packageDeclarationLineNum < lastLineNum) {
        String line = lines.get(packageDeclarationLineNum);
        if (line.startsWith("package ")) {
          packageDeclarationFound = true;
          break;
        }
        packageDeclarationLineNum++;
      }
      if (packageDeclarationFound) {
        var packageDeclarationLine =
            lines.get(packageDeclarationLineNum - 1);
        if (!packageDeclarationLine.startsWith(
            "package org.wharvex.jflap.")) {
          var newLine = packageDeclarationLine.replace("package ",
              "package org.wharvex.jflap.");
          FileLoader.replaceLine(file.toPath(),
              packageDeclarationLineNum - 1, newLine);
        }
      }
      break;
    }
  }
}
